#!/bin/bash
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

export ACME_ROOT=$HOME/code/acme
export HOMME_ROOT=$ACME_ROOT/components/homme
export Trilinos_DIR=$HOME/local/opt/trilinos-acme

NP=4
NLEVELS=26
NTRACERS=0

ARGS=(
    -D HOMME_PROJID=climalg

    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D BUILD_SHARED_LIBS=ON

    ### COMPILERS AND FLAGS ###
    -D CMAKE_Fortran_COMPILER=mpif90
    -D CMAKE_C_COMPILER=mpicc
    -D CMAKE_CXX_COMPILER=mpicxx
    -D ENABLE_OPENMP=OFF
    -D ENABLE_OPENACC=OFF

    ### TPLS ###
    -D HOMME_FIND_BLASLAPACK=ON
    -D WITH_PNETCDF=OFF

    ### PACKAGES CONFIGURATION ###
    -D BUILD_HOMME_PRIM=ON
        -D PRIM_NP=$NP
        -D PRIM_PLEV=$NLEVELS
        -D QSIZE_D=$NTRACERS
    -D BUILD_HOMME_SWIM=OFF
    -D BUILD_HOMME_SWEQX=OFF
    -D BUILD_HOMME_PREQX=OFF
    -D BUILD_HOMME_PREQX_ACC=OFF
)

cmake "${ARGS[@]}" $HOMME_ROOT

# Record environment for future
[[ -f build.env    ]] && mv build.env    build.env.old
[[ -f build.module ]] && mv build.module build.module.old
env          > build.env
module list &> build.module
