#!/bin/sh
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

# module load boost/1.58.0-cxx11
# module load gcc/5.2.0
# module load hdf5/1.8.11
# module load netcdf/4.3.0-wo4
# module load openmpi/1.10.0

ARGS=(
    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D ALBANY_TRILINOS_DIR="$HOME/local/opt/trilinos-albany"

    -D BUILD_SHARED_LIBS=ON

    ### COMPILERS AND FLAGS ###

    ### PACKAGES CONFIGURATION ###
    -D ENABLE_AERAS=OFF
    -D ENABLE_DEMO_PDES=ON
    -D ENABLE_FELIX=ON
    -D ENABLE_HYDRIDE=OFF
    -D ENABLE_LAME=OFF
    -D ENABLE_LCM=OFF
    -D ENABLE_MOR=OFF
    -D ENABLE_QCAD=OFF
    -D ENABLE_SG_MP=OFF

    ### MISC ###
    -D CMAKE_VERBOSE_MAKEFILE=ON

    )

cmake "${ARGS[@]}" $EXTRA_ARGS ../

# Record environment for future
[[ -f build.module ]] && mv build.module build.module.old
env          > build.env
module list &> build.module
