#!/bin/bash
EXTRA_ARGS=("$@")

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

export CPLUS_INCLUDE_PATH="$CPATH"

KOKKOS_DIR="$HOME/local/opt/kokkos"
ARGS=(
    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/arborx

    -D BUILD_SHARED_LIBS=ON

    ### TPLs ###
    -D ARBORX_ENABLE_MPI=ON
    -D CMAKE_PREFIX_PATH="$KOKKOS_DIR"

    ### COMPILERS AND FLAGS ###
    -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
    -D CMAKE_CXX_COMPILER="nvcc_wrapper"
    -D CMAKE_CXX_FLAGS="-lineinfo -DKOKKOS_ENABLE_PROFILING"

    ### MISC ###
    -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
    -D ARBORX_ENABLE_TESTS=ON
    -D ARBORX_ENABLE_EXAMPLES=ON
    -D ARBORX_ENABLE_BENCHMARKS=ON
    )

set -o pipefail
cmake -GNinja "${ARGS[@]}" "${EXTRA_ARGS[@]}" "${ARBORX_DIR:-../}" 2>&1 | tee configure.log
exit_status=$?

if [ $exit_status -eq 0 ]; then
  # Record environment for future
  [[ -f build.env    ]] && mv build.env    build.env.old
  [[ -f build.module ]] && mv build.module build.module.old
  env          > build.env
  module list -t | tail -n +2 &> build.module
fi
