#!/bin/bash
for i in `ls -d */`; do
  rm -f  $i/CMakeCache.txt
  rm -rf $i/CMakeFiles
done

# Record environment for future
[[ -f build.env    ]] && mv build.env    build.env.old
[[ -f build.module ]] && mv build.module build.module.old
env          > build.env
module list &> build.module

# Add --no-enable-fwd-packages if necessary
ARGS=(
  ../checkin-test.py -j 12
  --ctest-timeout=1200
  # --send-email-to=xap@ornl.gov
  --do-all
  --push
  # --append-test-results
  )

nice -n 19 "${ARGS[@]}" "$@"
