#!/bin/bash
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

export E3SM_ROOT=$HOME/code/e3sm
export HOMME_ROOT=$E3SM_ROOT/components/homme
export Trilinos_DIR=$HOME/local/opt/trilinos-fortrilinos

NETCDF_DIR=`spack find -p netcdf | tail -n 1 | awk '{print $2}'`
NETCDFF_DIR=`spack find -p netcdf-fortran | tail -n 1 | awk '{print $2}'`

[[ "$NETCDF_DIR" == "No" ]] && echo "Spack netcdf package not found" && exit 1
[[ "$NETCDFF_DIR" == "No" ]] && echo "Spack netcdf-fortran package not found" && exit 1


NP=4
NLEVELS=26
NTRACERS=0

ARGS=(
    -D HOMME_PROJID=climalg

    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D BUILD_SHARED_LIBS=OFF

    ### COMPILERS AND FLAGS ###
    -D CMAKE_Fortran_COMPILER=mpif90
        # -D CMAKE_Fortran_FLAGS="-Wtabs -Wno-unused-variable"
    -D CMAKE_C_COMPILER=mpicc
    -D CMAKE_CXX_COMPILER=mpicxx
    -D ENABLE_OPENMP=OFF
    -D ENABLE_OPENACC=OFF

    ### TPLS ###
    -D HOMME_FIND_BLASLAPACK=ON
    -D NetCDF_C_PATH="${NETCDF_DIR}"
    -D NetCDF_Fortran_PATH="${NETCDFF_DIR}"
    -D WITH_PNETCDF=OFF

    ### PACKAGES CONFIGURATION ###
    -D BUILD_HOMME_PREQX=OFF
    -D BUILD_HOMME_PREQX_ACC=OFF
    -D BUILD_HOMME_PRIM=OFF
        -D PRIM_NP=$NP
        -D PRIM_PLEV=$NLEVELS
        -D QSIZE_D=$NTRACERS
    -D BUILD_HOMME_SWEQX=OFF
    -D BUILD_HOMME_SWIM=ON
        -D SWIM_NP=$NP
    -D BUILD_HOMME_THETA=OFF

    # The way baseline works is like this:
    # 1. Pull a fresh unmodified copy of E3SM
    # 2. Build
    # 3. Run `make baseline` to produce gold baseline
    # 4. Modify soures and use a second build for development
    # 5. Compare builds against the baseline in the gold
    # More info here:
    #   wiki.ucar.edu/display/homme/How+to+run+the+regression+tests
    # This CMake var points to the gold baseline
    -D HOMME_BASELINE_DIR="`pwd`"
)

set -o pipefail
cmake "${ARGS[@]}" "$EXTRA_ARGS" $HOMME_ROOT | tee configure.log
exit_status=$?

if [ $exit_status -eq 0 ]; then
  # Record environment for future
  [[ -f build.env    ]] && mv build.env    build.env.old
  [[ -f build.module ]] && mv build.module build.module.old
  env          > build.env
  module list -t 2>&1 | tail -n +2 > build.module
fi
