#!/bin/bash
EXTRA_ARGS=("$@")

source $HOME/.personal/package_configs/preamble

export CPLUS_INCLUDE_PATH="$CPATH"

KOKKOS_DIR=$(readlink -f "${KOKKOS_DIR:-../}")
ARGS=(
    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/kokkos

    ### COMPILERS AND FLAGS ###
    -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
    -D CMAKE_CXX_COMPILER="$KOKKOS_DIR/bin/nvcc_wrapper"
    -D CMAKE_CXX_STANDARD=14

    ### MISC ###
    -D Kokkos_ENABLE_SERIAL=ON
    -D Kokkos_ENABLE_OPENMP=ON
    -D Kokkos_ENABLE_CUDA=ON
        -D Kokkos_ENABLE_CUDA_LAMBDA=ON
    -D Kokkos_ENABLE_DEPRECATED_CODE=OFF
    -D Kokkos_ARCH_PASCAL61=ON
    )
cmake_cmd="cmake -GNinja ${ARGS[@]} ${EXTRA_ARGS[@]} ${KOKKOS_DIR}"

source $HOME/.personal/package_configs/postamble
