#!/usr/bin/env bash
../generate_makefile.bash \
    --prefix="$HOME/local/opt/kokkos" \
    --with-serial \
    --with-openmp \
    --with-cuda \
    --with-cuda-options=enable_lambda,enable_uvm \
    --cxxstandard=c++14 \
    --arch=Pascal61 \
    # --compiler=???

exit_status=$?

if [ $exit_status -eq 0 ]; then
  # Record environment for future
  [[ -f build.env    ]] && mv build.env    build.env.old
  [[ -f build.module ]] && mv build.module build.module.old
  env          > build.env
  module list &> build.module
fi
