#!/bin/bash

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja


ARGS=(
    -D CMAKE_BUILD_TYPE=Debug

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/mfmg

    -D BUILD_SHARED_LIBS=ON

    ### COMPILERS AND FLAGS ###
    -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
    # According to https://github.com/ninja-build/ninja/wiki/FAQ, one is
    # required to force colored output by adding "-fdiagnostics-color"
    -D CMAKE_CXX_FLAGS="-Wall -Werror -fopenmp -Wpedantic -Wextra -Wshadow -fdiagnostics-color ${CMAKE_CXX_FLAGS}"

    ### TPLS ###
    -D DEAL_II_DIR=${HOME}/local/opt/dealii

    ### ETI ###

    ### PACKAGES CONFIGURATION ###
    -D MFMG_ENABLE_TESTS=ON
    # -D MFMG_ENABLE_ClangFormat=ON
  )

set -o pipefail
cmake -GNinja "${ARGS[@]}" $EXTRA_ARGS "${MFMG_DIR:-../../}" 2>&1 | tee configure.log
exit_status=$?

if [ $exit_status -eq 0 ]; then
  # Record environment for future
  [[ -f build.env    ]] && mv build.env    build.env.old
  [[ -f build.module ]] && mv build.module build.module.old
  env          > build.env
  module list -t 2>&1 | tail -n +2 > build.module
fi
