#!/bin/sh
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/

# An example
cmake \
    -D BUILD_SHARED_LIBS=ON \
    \
    -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=OFF \
    -D Trilinos_DEPS_XML_OUTPUT_FILE:FILEPATH="" \
    -D Trilinos_ENABLE_SHADOW_WARNINGS=OFF \
    \
    -D CMAKE_INSTALL_PREFIX:PATH=$HOME/local/opt/trilinos/ \
    -D CMAKE_BUILD_TYPE:STRING=RELEASE \
    \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=OFF \
    -D Teuchos_ENABLE_LONG_LONG_INT=ON \
    \
    -D TPL_ENABLE_MPI=ON \
    -D MPI_BASE_DIR=/home/aprokop/local/opt/openmpi-1.6.2/ \
    \
    -D CMAKE_CXX_FLAGS:STRING="-g -O3" \ # "-Wshadow -Wunused-parameter" \
    \
    -D TPL_ENABLE_Boost=OFF \
    -D TPL_Boost_INCLUDE_DIRS=/home/aprokop/local/opt/boost-1.52.0/include \
    -D TPL_Boost_LIBRARIES=/home/aprokop/local/opt/boost-1.52.0/lib/libboost_graph.so \
    \
    -D TPL_ENABLE_SuperLU=ON \
    -D TPL_SuperLU_INCLUDE_DIRS=/home/aprokop/local/opt/superlu-4.3/include/ \
    -D TPL_SuperLU_LIBRARIES=/home/aprokop/local/opt/superlu-4.3/lib/libsuperlu_4.3.so \
    \
    -D Trilinos_ENABLE_TESTS=OFF \
    -D Trilinos_ENABLE_OpenMP=OFF \
    -D Trilinos_ENABLE_Fortran=OFF \
    \
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
    -D Trilinos_ASSERT_MISSING_PACKAGES=OFF \
    \
    -D Trilinos_ENABLE_Amesos=ON \
    -D Trilinos_ENABLE_Amesos2=ON \
        -D Amesos2_ENABLE_SuperLU=ON \
        -D Amesos2_ENABLE_TESTS=ON \
    -D Trilinos_ENABLE_AztecOO=ON \
    -D Trilinos_ENABLE_Epetra=ON \
        -D Epetra_ENABLE_TESTS=ON \
    -D Trilinos_ENABLE_Xpetra=ON \
        -D Xpetra_ENABLE_Experimental=ON \
        -D Xpetra_ENABLE_TESTS=ON \
    -D Trilinos_ENABLE_Tpetra=ON \
        -D Tpetra_ENABLE_TESTS=ON \
    -D Trilinos_ENABLE_EpetraExt=ON \
    -D Trilinos_ENABLE_Ifpack=ON \
    -D Trilinos_ENABLE_Ifpack2=ON \
        -D Ifpack2_ENABLE_TESTS=ON \
    -D Trilinos_ENABLE_Kokkos=ON \
    -D Trilinos_ENABLE_ML=ON \
        -D ML_ENABLE_TESTS=ON \
    -D Trilinos_ENABLE_MueLu=ON \
        -D MueLu_ENABLE_Ifpack2=ON \
        -D MueLu_ENABLE_Amesos2=ON \
        -D MueLu_ENABLE_TESTS=ON \
        -D MueLu_ENABLE_EXAMPLES=ON \
        -D MueLu_ENABLE_PROFILING=ON \
        -D MueLu_INST_DOUBLE_INT_LONGLONGINT=ON \
        -D MueLu_ENABLE_EXPLICIT_INSTANTIATION=ON \
    -D Trilinos_ENABLE_Stratimikos=ON \
    -D Trilinos_ENABLE_Zoltan=ON \
    -D Trilinos_ENABLE_Zoltan2=ON \
        -D Zoltan2_ENABLE_TESTS=ON \
        -D Zoltan2_ENABLE_Experimental=ON \
    $EXTRA_ARGS \
    ../..
