#!/bin/sh
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

if [ "$OMPI_MPICXX" == "clang++" ]; then
    echo "This configuration requires using gcc"
    exit 1
fi

TRILINOS_PATH="$HOME/local/opt/trilinos-nalu"
YAML_PATH="$HOME/local/opt/yaml-cxx11-upstream"

ARGS=(
    -D Trilinos_DIR="${TRILINOS_PATH}"
    -D YAML_DIR=${YAML_PATH}
        -D YAML_LIBRARY="${YAML_PATH}/lib/libyaml-cpp.so"
    -D ENABLE_INSTALL=OFF
    )
cmake "${ARGS[@]}" $EXTRA_ARGS ../

# Record environment for future
env         > build.env
module list &> build.module
