#!/usr/bin/env bash
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/

TRILINOS_INSTALL=$HOME/local/opt/trilinos-nalu

ARGS=(
    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D ENABLE_INSTALL=OFF

    -D BUILD_SHARED_LIBS=ON

    -D Trilinos_DIR=${TRILINOS_INSTALL}

    ### COMPILERS AND FLAGS ###

    ### TPLS ###
 )
cmake "${ARGS[@]}" $EXTRA_ARGS ../

# Record environment for future
env         > build.env
module list &> build.module
