#!/usr/bin/env bash
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/

TRILINOS_INSTALL=$HOME/local/opt/trilinos-nalu

YAML_PATH=`spack find -p yaml-cpp | tail -n 1 | awk '{print $2}'`
ARGS=(
    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D ENABLE_INSTALL=OFF

    -D BUILD_SHARED_LIBS=ON

    -D Trilinos_DIR=${TRILINOS_INSTALL}

    -D ENABLE_YouCompleteMe=ON

    ### COMPILERS AND FLAGS ###

    ### TPLS ###
    -D YAML_DIR=${YAML_PATH}
        -D YAML_LIBRARY="${YAML_PATH}/lib/libyaml-cpp.so"


    ### PACKAGES CONFIGURATION ###
    -D ENABLE_TESTS=ON

    # -D TEST_TOLERANCE=".0001"
 )

set -o pipefail
cmake -GNinja "${ARGS[@]}" $EXTRA_ARGS "${NALU_DIR:-../..}" 2>&1 | tee configure.log
exit_status=$?

if [ $exit_status -eq 0 ]; then
  # Record environment for future
  [[ -f build.env    ]] && mv build.env    build.env.old
  [[ -f build.module ]] && mv build.module build.module.old
  env          > build.env
  module list -t 2>&1 | tail -n +2 > build.module
fi
