#!/bin/sh
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

# module load boost/1.57.0
# module load gcc/5.2.0
# module load hdf5/1.8.11
# module load netcdf/4.3.0-wo4
# module load openmpi/1.10.0

if [ "$OMPI_MPICXX" != "g++" ]; then
    echo "This configuration requires using gcc"
    exit 1
fi

BOOST_PATH="$HOME/local/opt/boost-1.57.0"
GLM_PATH="$HOME/local/include/glm"
HDF5_PATH="$HOME/local/opt/hdf5-1.8.11"
MPI_PATH="$HOME/local/opt/openmpi-1.10.0"
NETCDF_PATH="$HOME/local/opt/netcdf-wo4-4.3.0"
SUPERLU_PATH="$HOME/local/opt/superlu-4.3"

ARGS=(
    -D CMAKE_BUILD_TYPE=RELEASE

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/trilinos-albany

    -D BUILD_SHARED_LIBS=ON

    ### COMPILERS AND FLAGS ###
    -D CMAKE_CXX_FLAGS="-g"
    -D Trilinos_ENABLE_SHADOW_WARNINGS=OFF
    -D Phalanx_SHOW_DEPRECATED_WARNINGS=OFF

    ### TPLS ###
    -D TPL_ENABLE_MPI=ON
        -D MPI_BASE_DIR="${MPI_PATH}"
    -D TPL_ENABLE_Boost=ON
        -D Boost_INCLUDE_DIRS="${BOOST_PATH}/include"
        -D Boost_LIBRARY_DIRS="${BOOST_PATH}/lib/"
    -D TPL_ENABLE_BoostLib=ON
        -D BoostLib_INCLUDE_DIRS="${BOOST_PATH}/include"
        -D BoostLib_LIBRARY_DIRS="${BOOST_PATH}/lib/"
    -D TPL_ENABLE_BoostAlbLib=ON
        -D BoostAlbLib_INCLUDE_DIRS="${BOOST_PATH}/include"
        -D BoostAlbLib_LIBRARY_DIRS="${BOOST_PATH}/lib"
    -D TPL_ENABLE_GLM=ON
        -D TPL_GLM_INCLUDE_DIRS="${GLM_PATH}"
    -D TPL_ENABLE_HDF5=ON
        -D TPL_HDF5_INCLUDE_DIRS="${HDF5_PATH}/include"
        -D TPL_HDF5_LIBRARIES="${HDF5_PATH}/lib/libhdf5.so"
    -D TPL_ENABLE_Netcdf=ON
        -D TPL_Netcdf_INCLUDE_DIRS="${NETCDF_PATH}/include"
        -D TPL_Netcdf_LIBRARIES="${NETCDF_PATH}/lib/libnetcdf.so"
    -D TPL_ENABLE_SuperLU=ON
        -D TPL_SuperLU_INCLUDE_DIRS="${SUPERLU_PATH}/include/"
        -D TPL_SuperLU_LIBRARIES="${SUPERLU_PATH}/lib/libsuperlu_4.3.so"

    ### ETI ###
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
        -D Teuchos_ENABLE_LONG_LONG_INT=ON
        # -D Teuchos_ENABLE_COMPLEX=ON
        -D Tpetra_INST_COMPLEX_DOUBLE=OFF
        -D Tpetra_INST_COMPLEX_FLOAT=OFF
        -D Tpetra_INST_DOUBLE=ON
        -D Tpetra_INST_INT_INT=ON
        -D Tpetra_INST_INT_LONG_LONG=ON
        -D Tpetra_INST_INT_LONG=OFF
        -D Tpetra_INST_INT_UNSIGNED=OFF

    ### PACKAGES CONFIGURATION ###
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
    -D Trilinos_ASSERT_MISSING_PACKAGES=OFF

    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_EXAMPLES=OFF

    -D Trilinos_ENABLE_Amesos=ON
    -D Trilinos_ENABLE_Amesos2=ON
        -D Amesos2_ENABLE_KLU2=ON
            -D Teuchos_ENABLE_LONG_LONG_INT=ON
        -D Amesos2_ENABLE_SuperLU=ON
    -D Trilinos_ENABLE_Anasazi=ON
    -D Trilinos_ENABLE_AztecOO=ON
    -D Trilinos_ENABLE_Didasko=ON
    -D Trilinos_ENABLE_Epetra=ON
    -D Trilinos_ENABLE_EpetraExt=ON
        -D EpetraExt_ENABLE_HDF5=OFF
    -D Trilinos_ENABLE_FEI=ON
    -D Trilinos_ENABLE_GlobiPack=ON
    -D Trilinos_ENABLE_Ifpack=ON
    -D Trilinos_ENABLE_Ifpack2=ON
    -D Trilinos_ENABLE_Intrepid=ON
        -D HAVE_INTREPID_KOKKOSCORE=ON
    -D Trilinos_ENABLE_Isorropia=ON
    -D Trilinos_ENABLE_Kokkos=ON
        -D Trilinos_ENABLE_KokkosCore=ON
        -D Kokkos_ENABLE_Serial=ON
        -D Kokkos_ENABLE_OpenMP=OFF
        -D Kokkos_ENABLE_Pthread=OFF
    -D Trilinos_ENABLE_KokkosCore=ON
    -D Trilinos_ENABLE_Mesquite=ON
    -D Trilinos_ENABLE_ML=ON
    -D Trilinos_ENABLE_MOOCHO=ON
    -D Trilinos_ENABLE_MueLu=ON
        -D MueLu_ENABLE_Experimental=OFF
        -D MueLu_ENABLE_Ifpack2=ON
        -D MueLu_ENABLE_Amesos2=ON
    -D Trilinos_ENABLE_OptiPack=ON
    -D Trilinos_ENABLE_NOX=ON
    -D Trilinos_ENABLE_Phalanx=ON
        -D Phalanx_KOKKOS_DEVICE_TYPE="SERIAL"
        -D Phalanx_INDEX_SIZE_TYPE="INT"
        -D Phalanx_ENABLE_TEUCHOS_TIME_MONITOR=ON
    -D Trilinos_ENABLE_Piro=ON
    -D Trilinos_ENABLE_Rythmos=ON
    -D Trilinos_ENABLE_Sacado=ON
    # -D Trilinos_ENABLE_SEACAS=ON
        -D Trilinos_ENABLE_SEACASIoss=ON
        -D Trilinos_ENABLE_SEACASExodus=ON
    -D Trilinos_ENABLE_Shards=ON
    # -D Trilinos_ENABLE_STK=ON
        -D Trilinos_ENABLE_STKIO=ON
        -D Trilinos_ENABLE_STKMesh=ON
        # -D Trilinos_ENABLE_STKSearch=OFF
        # -D Trilinos_ENABLE_STKSearchUtil=OFF
        # -D Trilinos_ENABLE_STKTopology=ON
        # -D Trilinos_ENABLE_STKTransfer=ON
        # -D Trilinos_ENABLE_STKUtil=ON
    -D Trilinos_ENABLE_STKClassic=OFF
    -D Trilinos_ENABLE_Stokhos=ON
        -D Stokhos_ENABLE_TEUCHOS_TIME_MONITOR=ON
    -D Trilinos_ENABLE_Stratimikos=ON
        -D Stratimikos_ENABLE_TEUCHOS_TIME_MONITOR=ON
    -D Trilinos_ENABLE_Teko=ON
    -D Trilinos_ENABLE_ThreadPool=ON
    -D Trilinos_ENABLE_Thyra=ON
        -D Trilinos_ENABLE_ThyraTpetraAdapters=ON
    -D Trilinos_ENABLE_Tpetra=ON
    -D Trilinos_ENABLE_TrilinosCouplings=ON
    -D Trilinos_ENABLE_Xpetra=ON
        -D Xpetra_ENABLE_Experimental=ON
    -D Trilinos_ENABLE_Zoltan=ON
    -D Trilinos_ENABLE_Zoltan2=ON
        -D Zoltan2_ENABLE_Experimental=ON

    ### MISC ###
    -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
    -D CMAKE_VERBOSE_MAKEFILE=OFF
    -D Trilinos_VERBOSE_CONFIGURE=OFF
    -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES=ON
    -D Trilinos_DEPS_XML_OUTPUT_FILE=""

    )

# Cannot use ninja as some packages require Fortran
cmake "${ARGS[@]}" $EXTRA_ARGS ../../
