#!/bin/sh
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

SYSTEM_HEADERS=""
for header_dir in `echo $CPATH | sed 's/:/\ /g'`; do
  SYSTEM_HEADERS="$SYSTEM_HEADERS -isystem $header_dir"
done

CXX_FLAGS_COMPILER_SPECIFIC=""
if [ "$OMPI_MPICXX" == "g++" ]; then
    CXX_FLAGS_COMPILER_SPECIFIC="-Wno-unused-local-typedefs"
elif [ "$OMPI_MPICXX" == "clang++" ]; then
    CXX_FLAGS_COMPILER_SPECIFIC=""
fi

ARGS=(
    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D BUILD_SHARED_LIBS=ON

    -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES=OFF
    -D Trilinos_DEPS_XML_OUTPUT_FILE=""
    -D Trilinos_ENABLE_SHADOW_WARNINGS=ON

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/trilinos/
    -D CMAKE_EXPORT_COMPILE_COMMANDS=ON

    # Disable explicit instantiation, as it requires Tpetra
    # -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON

    -D TPL_ENABLE_MPI=ON
    -D MPI_BASE_DIR=/home/aprokop/local/opt/openmpi-1.8.3/

    -D CMAKE_CXX_FLAGS="-Wall -Wextra -Wno-unused-parameter $CXX_FLAGS_COMPILER_SPECIFIC $SYSTEM_HEADERS"

    -D TPL_ENABLE_SuperLU=ON
    -D TPL_SuperLU_INCLUDE_DIRS=/home/aprokop/local/opt/superlu-4.3/include/
    -D TPL_SuperLU_LIBRARIES=/home/aprokop/local/opt/superlu-4.3/lib/libsuperlu_4.3.so

    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_OpenMP=OFF
    -D Trilinos_ENABLE_Fortran=OFF

    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
    -D Trilinos_ASSERT_MISSING_PACKAGES=OFF

    -D Trilinos_NO_32BIT_GLOBAL_INDICES=OFF
    -D Trilinos_NO_64BIT_GLOBAL_INDICES=OFF

    -D Trilinos_ENABLE_Amesos=ON
    -D Trilinos_ENABLE_Amesos2=OFF
    -D Trilinos_ENABLE_AztecOO=ON
    -D Trilinos_ENABLE_Epetra=ON
        -D Epetra_ENABLE_Teuchos=ON
    -D Trilinos_ENABLE_EpetraExt=ON
    -D Trilinos_ENABLE_Galeri=ON
    -D Trilinos_ENABLE_Ifpack=ON
    -D Trilinos_ENABLE_Ifpack2=OFF
    -D Trilinos_ENABLE_Isorropia=OFF
    -D Trilinos_ENABLE_Kokkos=ON
    -D Trilinos_ENABLE_ML=OFF
    -D Trilinos_ENABLE_MueLu=ON
        -D MueLu_ENABLE_Experimental=ON
        -D MueLu_ENABLE_TESTS=ON
        -D MueLu_ENABLE_EXAMPLES=ON
        -D MueLu_ENABLE_DEBUG=ON
    -D Trilinos_ENABLE_Stratimikos=OFF
    -D Trilinos_ENABLE_Teuchos=ON
        -D Teuchos_ENABLE_COMPLEX=ON
    -D Trilinos_ENABLE_Thyra=OFF
    -D Trilinos_ENABLE_Tpetra=OFF
    -D Trilinos_ENABLE_Xpetra=ON
        -D Xpetra_ENABLE_Experimental=ON
        -D Xpetra_ENABLE_TESTS=ON
    -D Trilinos_ENABLE_Zoltan=ON
    -D Trilinos_ENABLE_Zoltan2=OFF
    )
# cmake "${ARGS[@]}" $EXTRA_ARGS ../../ 2>&1 | tee configure.log
cmake -GNinja "${ARGS[@]}" $EXTRA_ARGS "${TRILINOS_DIR:-../../}" 2>&1 | tee configure.log

# Record environment for future
[[ -f build.env    ]] && mv build.env    build.env.old
[[ -f build.module ]] && mv build.module build.module.old
env          > build.env
module list &> build.module
