#!/bin/sh
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

ARGS=(
    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/trilinos-dtk/

    -D BUILD_SHARED_LIBS=ON

    ### COMPILERS AND FLAGS ###
    -D Trilinos_TPL_SYSTEM_INCLUDE_DIRS=ON
    -D Trilinos_ENABLE_CXX11=ON
        -D Trilinos_CXX11_FLAGS="-std=c++11 -expt-extended-lambda"
    -D CMAKE_CXX_FLAGS="-Wall \
        -lineinfo -arch=sm_61 \
        -DKOKKOSP_ENABLE_PROFILING \
        -Xcudafe --diag_suppress=initialization_not_reachable \
        -Xcudafe --diag_suppress=cc_clobber_ignored \
        -Xcudafe --diag_suppress=conversion_function_not_usable \
        -Xcudafe --diag_suppress=code_is_unreachable"
    -D Trilinos_ENABLE_Fortran=OFF
    -D Trilinos_ENABLE_SHADOW_WARNINGS=ON

    ### TPLS ###
    -D TPL_ENABLE_MPI=ON
        -D MPI_EXEC_POST_NUMPROCS_FLAGS="-bind-to;socket;-map-by;socket"
    -D TPL_ENABLE_BLAS=ON
    -D TPL_ENABLE_LAPACK=ON
    -D TPL_ENABLE_CUDA=ON
    -D TPL_ENABLE_CUSPARSE=ON
    -D TPL_ENABLE_HWLOC=OFF
    -D TPL_ENABLE_Boost=ON
    -D TPL_ENABLE_BoostLib=ON
    -D TPL_ENABLE_Libmesh=OFF
    -D TPL_ENABLE_MOAB=OFF

    ### ETI ###
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
        -D Tpetra_INST_INT_UNSIGNED_LONG=ON
        -D Tpetra_INST_INT_LONG_LONG=OFF
    -D Kokkos_ENABLE_Cuda_UVM=ON
    -D Kokkos_ENABLE_Cuda_Lambda=ON
    -D Kokkos_ENABLE_Serial=ON
    -D Tpetra_INST_SERIAL=ON

    ### PACKAGES CONFIGURATION ###
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
    -D Trilinos_ASSERT_MISSING_PACKAGES=OFF

    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_EXAMPLES=OFF

    -D Trilinos_EXTRA_REPOSITORIES="DataTransferKit"

    -D Trilinos_ENABLE_Tpetra=ON
    -D Trilinos_ENABLE_DataTransferKit=ON
        -D DataTransferKit_ENABLE_YouCompleteMe=ON
        -D DataTransferKit_ENABLE_ClangFormat=ON
        -D DataTransferKit_ENABLE_DBC=ON
        -D DataTransferKit_ENABLE_TESTS=ON
        -D DataTransferKit_ENABLE_EXAMPLES=ON
    -D Trilinos_ENABLE_STK=OFF
        # -D Trilinos_ENABLE_STKTopology=ON

    ### MISC ###
    -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
    -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES=OFF
    -D Trilinos_DEPS_XML_OUTPUT_FILE=""

    )

# cmake -GNinja "${ARGS[@]}" $EXTRA_ARGS ../../ | tee configure.log
cmake "${ARGS[@]}" $EXTRA_ARGS ../../ | tee configure.log

# Record environment for future
[[ -f build.env    ]] && mv build.env    build.env.old
[[ -f build.module ]] && mv build.module build.module.old
env          > build.env
module list &> build.module
