#!/bin/sh
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

# module load boost/1.58.0-cxx11
# module load gcc/5.2.0
# module load hdf5/1.8.11
# module load netcdf/4.3.0-wo4
# module load openmpi/1.10.0

SYSTEM_HEADERS=""
for header_dir in `echo $CPATH | sed 's/:/\ /g'`; do
  SYSTEM_HEADERS="$SYSTEM_HEADERS -isystem $header_dir"
done

if [ "$OMPI_MPICXX" != "g++" ]; then
    echo "This configuration requires using gcc"
    exit 1
fi

BOOST_PATH="$HOME/local/opt/boost-1.58.0-cxx11"
HDF5_PATH="$HOME/local/opt/hdf5-1.8.11"
MPI_PATH="$HOME/local/opt/openmpi-1.10.0"
NETCDF_PATH="$HOME/local/opt/netcdf-wo4-4.3.0"
SUPERLU_PATH="$HOME/local/opt/superlu-4.3"

ARGS=(
    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/trilinos-drekar-reuse

    -D BUILD_SHARED_LIBS=ON

    ### COMPILERS AND FLAGS ###
    -D Trilinos_ENABLE_Fortran=ON
    -D CMAKE_CXX_FLAGS="$SYSTEM_HEADERS"
    -D Trilinos_ENABLE_SHADOW_WARNINGS=OFF

    ### TPLS ###
    -D TPL_ENABLE_MPI=ON
        -D MPI_BASE_DIR="${MPI_PATH}"
    -D TPL_ENABLE_Boost=ON
        -D Boost_INCLUDE_DIRS="${BOOST_PATH}/include"
        -D Boost_LIBRARY_DIRS="${BOOST_PATH}/lib/"
    -D TPL_ENABLE_BoostLib=ON
        -D BoostLib_INCLUDE_DIRS="${BOOST_PATH}/include"
        -D BoostLib_LIBRARY_DIRS="${BOOST_PATH}/lib/"
    -D TPL_ENABLE_HDF5=ON
        -D TPL_HDF5_INCLUDE_DIRS="${HDF5_PATH}/include"
        -D TPL_HDF5_LIBRARIES="${HDF5_PATH}/lib/libhdf5.so"
    -D TPL_ENABLE_Netcdf=ON
        -D TPL_Netcdf_INCLUDE_DIRS="${NETCDF_PATH}/include"
        -D TPL_Netcdf_LIBRARIES="${NETCDF_PATH}/lib/libnetcdf.so"
    -D TPL_ENABLE_SuperLU=ON
        -D TPL_SuperLU_INCLUDE_DIRS="${SUPERLU_PATH}/include/"
        -D TPL_SuperLU_LIBRARIES="${SUPERLU_PATH}/lib/libsuperlu_4.3.so"
    -D TPL_ENABLE_Matio=OFF
    -D TPL_ENABLE_X11=OFF

    ### ETI ###
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
        -D Teuchos_ENABLE_LONG_LONG_INT=OFF
        -D Tpetra_INST_INT_LONG_LONG=OFF
        -D Tpetra_INST_COMPLEX_DOUBLE=OFF
        -D Drekar_ENABLE_EXPLICIT_INSTANTIATION=ON
        -D DrekarMHD_ENABLE_EXPLICIT_INSTANTIATION=ON
        -D Kokkos_ENABLE_Pthread=OFF

    ### PACKAGES CONFIGURATION ###
    -D Trilinos_EXTRA_REPOSITORIES="DrekarResearch,DrekarBase"
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
    -D Trilinos_ASSERT_MISSING_PACKAGES=OFF

    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_EXAMPLES=OFF

    -D Trilinos_ENABLE_Amesos=ON
    -D Trilinos_ENABLE_Amesos2=ON
    -D Trilinos_ENABLE_Belos=ON
    -D Trilinos_ENABLE_Drekar=ON
        -D Drekar_ENABLE_DrekarMHD=ON
        -D Drekar_ENABLE_TESTS=ON
        -D Drekar_ENABLE_EXAMPLES=ON
    -D Trilinos_ENABLE_DrekarMHD=ON
    -D Trilinos_ENABLE_EpetraExt=ON
        -D EpetraExt_ENABLE_HDF5=OFF
    -D Trilinos_ENABLE_FEI=ON
    -D Trilinos_ENABLE_Intrepid=ON
        -D Intrepid_ENABLE_DEBUG_INF_CHECK=OFF
    -D Trilinos_ENABLE_Ifpack2=ON
    -D Trilinos_ENABLE_Kokkos=ON
        -D Trilinos_ENABLE_KokkosCore=ON
    -D Trilinos_ENABLE_ML=ON
    -D Trilinos_ENABLE_MueLu=ON
        -D MueLu_ENABLE_TESTS=ON
        -D MueLu_ENABLE_EXAMPLES=ON
    -D Trilinos_ENABLE_NOX=ON
        -D NOX_ENABLE_TESTS=ON
    -D Trilinos_ENABLE_Panzer=ON
    -D Trilinos_ENABLE_Piro=ON
    -D Trilinos_ENABLE_Shards=ON
    -D Trilinos_ENABLE_Teuchos=ON
    -D Trilinos_ENABLE_SEACAS=ON
        # -D SEACAS_ENABLE_NETCDF4_SUPPORT=ON
        -D SEACASExodus_ENABLE_MPI=OFF
    -D Trilinos_ENABLE_STKClassic=ON
        -D Trilinos_ENABLE_STKIO=OFF
        -D Trilinos_ENABLE_STKMesh=OFF
        -D Trilinos_ENABLE_STKSearch=OFF
        -D Trilinos_ENABLE_STKSearchUtil=OFF
        -D Trilinos_ENABLE_STKTopology=OFF
        -D Trilinos_ENABLE_STKTransfer=OFF
        -D Trilinos_ENABLE_STKUtil=OFF
    -D Trilinos_ENABLE_Stokhos=OFF
    -D Trilinos_ENABLE_Stratimikos=ON
    -D Trilinos_ENABLE_Teko=ON
    -D Trilinos_ENABLE_Tpetra=ON
        -D Tpetra_ENABLE_TESTS=ON
        -D Tpetra_ENABLE_MMM_Timings=ON
    -D Trilinos_ENABLE_Xpetra=ON
        -D Xpetra_ENABLE_TESTS=ON
    -D Trilinos_ENABLE_Zoltan=ON
    -D Trilinos_ENABLE_Zoltan2=ON
        -D Zoltan2_ENABLE_Experimental=ON

    ### MISC ###
    -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
    -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES=ON
    -D Trilinos_DEPS_XML_OUTPUT_FILE=""

    )
cmake "${ARGS[@]}" $EXTRA_ARGS "${TRILINOS_DIR:-../../}" 2>&1 | tee configure.log

# Record environment for future
[[ -f build.env    ]] && mv build.env    build.env.old
[[ -f build.module ]] && mv build.module build.module.old
env          > build.env
module list &> build.module
