#!/bin/bash
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

SWIG_DIR="$HOME/code/swig"
ARGS=(
    -D CMAKE_BUILD_TYPE=RelWithDebInfo

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/trilinos-fortrilinos

    -D BUILD_SHARED_LIBS=ON

    ### COMPILERS AND FLAGS ###
    -D Trilinos_ENABLE_Fortran=ON
    -D Trilinos_TPL_SYSTEM_INCLUDE_DIRS=ON
    -D CMAKE_CXX_FLAGS="-Wall -Wpedantic"

    ### TPLs ###
    -D TPL_ENABLE_MPI=ON
    -D TPL_ENABLE_BLAS=ON
    -D TPL_ENABLE_LAPACK=ON
    -D TPL_ENABLE_Pthread=OFF
      -D SWIG_EXECUTABLE="$SWIG_DIR/swig"
      -D SWIG_DIR="$SWIG_DIR/Lib"

    ### ETI ###
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
        -D Tpetra_INST_INT_INT=OFF
        -D Tpetra_INST_INT_LONG=OFF
        -D Tpetra_INST_INT_LONG_LONG=ON

    ### PACKAGES CONFIGURATION ###
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF

    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_EXAMPLES=OFF

    -D Trilinos_ENABLE_Amesos2=ON
    -D Trilinos_ENABLE_Anasazi=ON
    -D Trilinos_ENABLE_Belos=ON
    -D Trilinos_ENABLE_Epetra=OFF
    -D Trilinos_ENABLE_Galeri=OFF
    -D Trilinos_ENABLE_Ifpack2=ON
    -D Trilinos_ENABLE_MueLu=ON
    -D Trilinos_ENABLE_Stratimikos=ON
    -D Trilinos_ENABLE_Tpetra=ON
    -D Trilinos_ENABLE_Thyra=ON

    ### FORTRILINOS ###
    -D Trilinos_ENABLE_ForTrilinos=ON
        -D ForTrilinos_ENABLE_DeveloperMode=ON
        -D ForTrilinos_ENABLE_EXAMPLES=ON
        -D ForTrilinos_ENABLE_TESTS=ON
        -D ForTrilinos_ENABLE_ReadTheDocs=ON
    )

# cmake -GNinja "${ARGS[@]}" $EXTRA_ARGS ../../ | tee configure.log
cmake "${ARGS[@]}" $EXTRA_ARGS ../../ | tee configure.log

# Record environment for future
[[ -f build.env    ]] && mv build.env    build.env.old
[[ -f build.module ]] && mv build.module build.module.old
env          > build.env
module list &> build.module
