#!/bin/bash
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

# module load openmpi/1.10.0
# module load gcc/5.2.0
# module load boost/1.58.0-cxx11

SYSTEM_HEADERS=""
for header_dir in `echo $CPATH | sed 's/:/\ /g'`; do
  SYSTEM_HEADERS="$SYSTEM_HEADERS -isystem $header_dir"
done

BOOST="true"
if [ "$BOOST" == "true" ] && [ "$OMPI_MPICXX" == "clang++" ]; then
    echo "This configuration (BOOST) requires using gcc"
    exit 1
fi

CXX_FLAGS_COMPILER_SPECIFIC=""
if [ "$OMPI_MPICXX" == "g++" ]; then
    CXX_FLAGS_COMPILER_SPECIFIC="-Wno-unused-local-typedefs"
elif [ "$OMPI_MPICXX" == "clang++" ]; then
    CXX_FLAGS_COMPILER_SPECIFIC=""
fi


BOOST_PATH="$HOME/local/opt/boost-1.58.0-cxx11/"
MPI_PATH="$HOME/local/opt/openmpi-1.10.0/"
# MPI_PATH="$HOME/local/opt/mpich-3.1.3/"
SUPERLU_PATH="$HOME/local/opt/superlu-4.3/"

ARGS=(
    -D CMAKE_BUILD_TYPE=DEBUG

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/trilinos/

    -D BUILD_SHARED_LIBS=ON

    ### COMPILERS AND FLAGS ###
    -D Trilinos_ENABLE_Fortran=OFF
    -D Trilinos_TPL_SYSTEM_INCLUDE_DIRS=ON
    -D Trilinos_ENABLE_SHADOW_WARNINGS=ON
    -D CMAKE_C_FLAGS="-Wall -Wextra -std=c99 -pedantic -Wno-unused-parameter $CXX_FLAGS_COMPILER_SPECIFIC $SYSTEM_HEADERS"
    -D CMAKE_CXX_FLAGS="-Wall -Wextra -pedantic -Wno-unused-parameter $CXX_FLAGS_COMPILER_SPECIFIC $SYSTEM_HEADERS"

    ### TPLS ###
    -D TPL_ENABLE_MPI=ON
        -D MPI_BASE_DIR="${MPI_PATH}"
    -D TPL_ENABLE_SuperLU=ON
        -D TPL_SuperLU_INCLUDE_DIRS="${SUPERLU_PATH}/include/"
        -D TPL_SuperLU_LIBRARIES="${SUPERLU_PATH}/lib/libsuperlu_4.3.so"
    -D TPL_ENABLE_BinUtils=ON

    ### ETI ###
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
        -D Teuchos_ENABLE_COMPLEX=ON
        -D Tpetra_INST_COMPLEX_DOUBLE=ON
        # -D Tpetra_INST_FLOAT=ON
        # -D Tpetra_INST_COMPLEX_FLOAT=ON
        # -D MueLu_INST_COMPLEX_INT_INT=ON

    ### PACKAGES CONFIGURATION ###
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
    -D Trilinos_ASSERT_MISSING_PACKAGES=OFF

    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_EXAMPLES=OFF

    -D Trilinos_ENABLE_Amesos=ON
    -D Trilinos_ENABLE_Amesos2=ON
        -D Amesos2_ENABLE_KLU2=ON
        -D Amesos2_ENABLE_SuperLU=ON
    -D Trilinos_ENABLE_AztecOO=ON
    -D Trilinos_ENABLE_Epetra=ON
        -D Epetra_ENABLE_Teuchos=ON
    -D Trilinos_ENABLE_EpetraExt=ON
    -D Trilinos_ENABLE_Ifpack=ON
    -D Trilinos_ENABLE_Ifpack2=ON
    -D Trilinos_ENABLE_Isorropia=ON
    -D Trilinos_ENABLE_Kokkos=ON
    -D Trilinos_ENABLE_ML=ON
        -D ML_ENABLE_TESTS=ON
    -D Trilinos_ENABLE_MueLu=ON
        -D MueLu_ENABLE_Experimental=ON
        -D MueLu_ENABLE_TESTS=ON
        -D MueLu_ENABLE_EXAMPLES=ON
        -D MueLu_ENABLE_DEBUG=ON
        -D MueLu_ENABLE_Amesos2=ON
        -D MueLu_ENABLE_Ifpack2=ON
        # -D MueLu_ENABLE_PROFILING=ON
    -D Trilinos_ENABLE_Stratimikos=ON
    -D Trilinos_ENABLE_Teko=ON
    -D Trilinos_ENABLE_Teuchos=ON
        -D Teuchos_ENABLE_DEBUG=ON
        -D Teuchos_ENABLE_STACKTRACE=ON
    -D Trilinos_ENABLE_Thyra=ON
    -D Trilinos_ENABLE_Tpetra=ON
    -D Trilinos_ENABLE_Xpetra=ON
        -D Xpetra_ENABLE_Experimental=ON
        -D Xpetra_ENABLE_EXAMPLES=ON
        -D Xpetra_ENABLE_TESTS=ON
    -D Trilinos_ENABLE_Zoltan=ON
    -D Trilinos_ENABLE_Zoltan2=ON
        -D Zoltan2_ENABLE_Experimental=ON
        -D Zoltan2_ENABLE_TESTS=ON

    ### MISC ###
    -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
    -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES=ON
    -D Trilinos_DEPS_XML_OUTPUT_FILE=""

    )
ARGS_BOOST=(
    -D TPL_ENABLE_Boost=ON
        -D Boost_INCLUDE_DIRS="${BOOST_PATH}/include"
        -D Boost_LIBRARY_DIRS="${BOOST_PATH}/lib/"
    -D TPL_ENABLE_BoostLib=ON
        -D BoostLib_INCLUDE_DIRS="${BOOST_PATH}/include"
        -D BoostLib_LIBRARY_DIRS="${BOOST_PATH}/lib/"

        -D MueLu_ENABLE_Boost_for_real=ON
    )
if [ "$BOOST" == "true" ]; then
    ARGS=( "${ARGS[@]}" "${ARGS_BOOST[@]}" )
fi

# cmake "${ARGS[@]}" $EXTRA_ARGS ../../ | tee configure.log
cmake -GNinja "${ARGS[@]}" $EXTRA_ARGS ../../ | tee configure.log
exit_status=$?

if [ $exit_status -eq 0 ]; then
  # Record environment for future
  [[ -f build.env    ]] && mv build.env    build.env.old
  [[ -f build.module ]] && mv build.module build.module.old
  env          > build.env
  module list &> build.module
fi
