#!/bin/bash
EXTRA_ARGS=$@

rm -f  CMakeCache.txt
rm -rf CMakeFiles/
rm -f  build.ninja
rm -f  rules.ninja

ARGS=(
    -D CMAKE_BUILD_TYPE=RELWITHDEBINFO

    -D CMAKE_INSTALL_PREFIX=$HOME/local/opt/trilinos-kokkos-openmp/

    -D BUILD_SHARED_LIBS=ON

    ### COMPILERS AND FLAGS ###
    -D Trilinos_ENABLE_Fortran=OFF
    -D Trilinos_TPL_SYSTEM_INCLUDE_DIRS=ON
    -D CMAKE_CXX_FLAGS="-Wall -ansi -pedantic -Wno-unknown-pragmas -Wno-narrowing -Wno-pragmas -Wno-unused-but-set-variable -Wno-inline -Wshadow"

    ### TPLS ###
    -D TPL_ENABLE_MPI=ON
        -D MPI_EXEC_POST_NUMPROCS_FLAGS="-bind-to;socket;-map-by;socket"
    -D TPL_ENABLE_BLAS=ON
    -D TPL_ENABLE_LAPACK=ON
    -D Trilinos_ENABLE_OpenMP=ON
    -D TPL_ENABLE_HWLOC=OFF

    ### ETI ###
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON
        -D Teuchos_ENABLE_COMPLEX=OFF
        -D Teuchos_ENABLE_LONG_LONG_INT=OFF
        -D Tpetra_INST_INT_INT=ON
        -D Tpetra_INST_INT_UNSIGNED=OFF
        -D Tpetra_INST_INT_LONG=OFF
        -D Tpetra_INST_INT_LONG_LONG=OFF
        -D Tpetra_INST_DOUBLE=ON
        -D Tpetra_INST_FLOAT=OFF
        -D Tpetra_INST_COMPLEX_DOUBLE=OFF
        -D Tpetra_INST_COMPLEX_FLOAT=OFF
        -D Tpetra_INST_SERIAL=ON
        -D Kokkos_ENABLE_Serial=ON
        -D Kokkos_ENABLE_OpenMP=ON
        -D Kokkos_ENABLE_Pthread=OFF

    ### PACKAGES CONFIGURATION ###
    -D Trilinos_ENABLE_ALL_PACKAGES=OFF
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF
    -D Trilinos_ASSERT_MISSING_PACKAGES=OFF

    -D Trilinos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_EXAMPLES=OFF

    -D Trilinos_ENABLE_Amesos=ON
    -D Trilinos_ENABLE_Amesos2=ON
        -D Amesos2_ENABLE_KLU2=ON
    -D Trilinos_ENABLE_AztecOO=ON
    -D Trilinos_ENABLE_Epetra=ON
        -D Epetra_ENABLE_Teuchos=ON
    -D Trilinos_ENABLE_EpetraExt=ON
    -D Trilinos_ENABLE_Ifpack=ON
    -D Trilinos_ENABLE_Ifpack2=ON
    -D Trilinos_ENABLE_Isorropia=ON
    -D Trilinos_ENABLE_Kokkos=ON
        # -D Kokkos_ENABLE_Profiling=OFF
        -D Kokkos_ENABLE_Debug_Bounds_Check=ON
        -D Kokkos_ENABLE_EXAMPLES=OFF
        -D Kokkos_ENABLE_TESTS=OFF
    -D Trilinos_ENABLE_ML=ON
    -D Trilinos_ENABLE_MueLu=ON
        -D MueLu_ENABLE_Experimental=ON
        -D MueLu_ENABLE_Kokkos_Refactor=ON
        -D MueLu_ENABLE_TESTS=ON
        -D MueLu_ENABLE_EXAMPLES=ON
        -D MueLu_ENABLE_DEBUG=ON
        # -D MueLu_ENABLE_PROFILING=ON
    -D Trilinos_ENABLE_ShyLU=OFF
    -D Trilinos_ENABLE_Stratimikos=ON
    -D Trilinos_ENABLE_Teuchos=ON
    -D Trilinos_ENABLE_Teko=OFF
    -D Trilinos_ENABLE_Thyra=ON
    -D Trilinos_ENABLE_Tpetra=ON
        -D Tpetra_ENABLE_MMM_Timings=ON
    -D Trilinos_ENABLE_TrilinosCouplings=OFF
        -D TrilinosCouplings_ENABLE_EXAMPLES=ON
    -D Trilinos_ENABLE_Xpetra=ON
        -D Xpetra_ENABLE_Experimental=ON
        -D Xpetra_ENABLE_Kokkos_Refactor=ON
        -D Xpetra_ENABLE_EXAMPLES=ON
        -D Xpetra_ENABLE_TESTS=ON
    -D Trilinos_ENABLE_Zoltan=ON
    -D Trilinos_ENABLE_Zoltan2=ON
        -D Zoltan2_ENABLE_Experimental=ON

    ### MISC ###
    -D CMAKE_EXPORT_COMPILE_COMMANDS=ON
    -D Trilinos_ENABLE_YouCompleteMe=ON
    -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES=ON
    -D Trilinos_DEPS_XML_OUTPUT_FILE=""

    )

set -o pipefail
cmake -GNinja "${ARGS[@]}" $EXTRA_ARGS "${TRILINOS_DIR:-../../}" 2>&1 | tee configure.log
exit_status=$?

if [ $exit_status -eq 0 ]; then
  # Record environment for future
  [[ -f build.env    ]] && mv build.env    build.env.old
  [[ -f build.module ]] && mv build.module build.module.old
  env          > build.env
  module list -t 2>&1 | tail -n +2 > build.module
fi
